services:
  ticketflow.api:
    image: ticketflow.api
    build:
      context: .
      dockerfile: TicketFlow.Api/Dockerfile

  db:
    image: postgres:latest
    container_name: postgres_ticketflow
    environment:
      POSTGRES_DB: ticketflow_db
      POSTGRES_USER: ticketflow_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    profiles:
      - db
      - deps

volumes:
  db_data: